version: "3.8"

services:
  musicgen:
    build: .
    container_name: musicgen-medium-api
    restart: unless-stopped

    ports:
      - "7880:7880"

    environment:
      - MUSICGEN_MODEL=facebook/musicgen-medium
      - HF_HOME=/app/hf_cache
      - MUSICGEN_MELODY_MODEL=facebook/musicgen-melody

    # Si quieres GPU (RTX 3070), deja esto.
    # Si prefieres CPU, comenta todo el bloque deploy.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

    volumes:
      - ./outputs:/outputs
      - ./hf_cache:/app/hf_cache
